version: "3.9"

services:
  video-uploader-service:
    build: .
    container_name: video-uploader-service
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_SQS_QUEUE_URL=${AWS_SQS_QUEUE_URL}
      # Descomente se usar LocalStack ou outro endpoint compat√≠vel
      # - AWS_S3_ENDPOINT=http://localstack:4566
      # - AWS_SQS_ENDPOINT=http://localstack:4566
    restart: unless-stopped


