apiVersion: v1
kind: ConfigMap
metadata:
  name: video-uploader-config
data:
  aws.region: "us-east-1"
  aws.s3.bucket: "my-video-bucket"
  aws.sqs.queueUrl: "https://sqs.us-east-1.amazonaws.com/123456789012/video-queue"
  aws.s3.endpoint: ""
  aws.sqs.endpoint: ""


