apiVersion: v1
kind: Service
metadata:
  name: video-uploader-service
spec:
  selector:
    app: video-uploader-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP


