apiVersion: v1
kind: ServiceAccount
metadata:
  name: video-uploader-service-account
  annotations:
    # Substitua pelo ARN da sua IAM role
    # Exemplo: eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/video-uploader-role
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/video-uploader-role
